from __future__ import annotations

import argparse
import warnings
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import seaborn as sns
from scipy.spatial.distance import cosine, pdist
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.manifold import TSNE
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")


HS_DIR  = Path("Narratives3/hidden_states_by_model")
OUT_DIR = Path("Narratives3/hidden_state_viz")

FIG_DPI      = 150
RANDOM_STATE = 42


GEN_COLORS = {"female": "#1EE9C4", "male": "#E58F1E"}
FAM_COLORS = {
    "llama":     "#4C72B0",
    "mistral":   "#DD8452",
    "qwen":      "#55A868",
    "gemma":     "#C44E52",
    "gpt-oss":   "#8172B2",   # open-source GPT-style models (e.g. ollama-gptoss)
    "gpt":       "#9C59A0",   # OpenAI API models — no hidden states extractable
    "anthropic": "#E05A2B",   # Anthropic API models — no hidden states extractable
}

REG_COLORS = {
    "North America": "#4C72B0", "Latin America": "#DD8452",
    "MENA": "#55A868", "Sub-Saharan Africa": "#C44E52",
    "South Asia": "#8172B2", "East/SE Asia": "#64B5CD",
    "Europe/Oceania": "#FF800E",
}
REGION_MAP = {
    "United States": "North America",  "Canada": "North America",
    "Mexico": "Latin America",         "Brazil": "Latin America",
    "Argentina": "Latin America",      "Colombia": "Latin America",
    "United Arab Emirates": "MENA",    "Saudi Arabia": "MENA",
    "Iran": "MENA",                    "Egypt": "MENA",
    "Turkey": "MENA",                  "Morocco": "MENA",
    "Nigeria": "Sub-Saharan Africa",   "Kenya": "Sub-Saharan Africa",
    "Ethiopia": "Sub-Saharan Africa",  "South Africa": "Sub-Saharan Africa",
    "Ghana": "Sub-Saharan Africa",
    "India": "South Asia",             "Sri Lanka": "South Asia",
    "Pakistan": "South Asia",
    "Japan": "East/SE Asia",           "China": "East/SE Asia",
    "South Korea": "East/SE Asia",     "Indonesia": "East/SE Asia",
    "Thailand": "East/SE Asia",        "Vietnam": "East/SE Asia",
    "Philippines": "East/SE Asia",
    "Russia": "Europe/Oceania",        "Germany": "Europe/Oceania",
    "Greece": "Europe/Oceania",        "Italy": "Europe/Oceania",
    "France": "Europe/Oceania",        "Spain": "Europe/Oceania",
    "Poland": "Europe/Oceania",        "Australia": "Europe/Oceania",
}




def _save(fig: plt.Figure, path: Path) -> None:
    fig.savefig(path, dpi=FIG_DPI, bbox_inches="tight")
    plt.close(fig)
    print(f"    saved → {path.name}")


def _pca2(X: np.ndarray) -> np.ndarray:
    n_comp = min(2, X.shape[0] - 1, X.shape[1])
    return PCA(n_components=n_comp, random_state=RANDOM_STATE).fit_transform(X)


def _tsne2(X: np.ndarray) -> np.ndarray:
    pca50 = PCA(n_components=min(50, X.shape[1], X.shape[0] - 1),
                random_state=RANDOM_STATE).fit_transform(X)
    return TSNE(n_components=2, perplexity=min(40, len(X) // 4),
                max_iter=600, init="pca", learning_rate="auto",
                random_state=RANDOM_STATE).fit_transform(pca50)


def _centroid_cos_dist(vecs: np.ndarray, mask_a: np.ndarray,
                       mask_b: np.ndarray) -> float:
    ca, cb = vecs[mask_a].mean(0), vecs[mask_b].mean(0)
    return float(cosine(ca, cb))


def _probe_acc(X: np.ndarray, y: np.ndarray, cv: int = 5) -> float:
    Xs = StandardScaler().fit_transform(X)
    clf = LogisticRegression(max_iter=300, C=1.0, solver="lbfgs")
    scores = cross_val_score(
        clf, Xs, y,
        cv=StratifiedKFold(min(cv, int(y.sum()), int((~y.astype(bool)).sum())),
                           shuffle=True, random_state=RANDOM_STATE),
        scoring="accuracy",
    )
    return float(scores.mean())


def _panel_layer_indices(n_layers: int, requested: list[int] | None) -> list[int]:
    if requested:
        return [l for l in requested if l < n_layers]
    # default: embedding + 4 evenly spaced including final
    idxs = [0]
    for frac in [0.25, 0.50, 0.75, 1.0]:
        idx = round(frac * (n_layers - 1))
        if idx not in idxs:
            idxs.append(idx)
    return idxs


# Per-model visualisations 

def describe_npy(hs: np.ndarray, model_key: str,
                 hf_id: str, out: Path) -> None:
    """Write a plain-text description of the array to know what was loaded."""
    n, L, H = hs.shape
    lines = [
        f"File: hidden_states_{model_key}.npy",
        f"HF model: {hf_id}",
        f"",
        f"Array shape: ({n}, {L}, {H})",
        f"  axis 0 : {n} stories generated by {model_key}",
        f"  axis 1 : {L} layers",
        f"             layer  0  : token embedding output",
        f"             layers 1..{L-1}: transformer block outputs",
        f"  axis 2 : {H}-dimensional hidden state vector per story per layer",
        f"",
        f"Each vector [story_i, layer_j, :] is the mean of all token",
        f"hidden states in story_i at transformer depth layer_j.",
        f"",
        f"Memory: {hs.nbytes / 1e6:.1f} MB  (float32)",
    ]
    path = out / "00_what_is_npy.txt"
    path.write_text("\n".join(lines))
    for line in lines:
        print("   ", line)
    print()


def plot_pca_final_layer(hs: np.ndarray, meta: pd.DataFrame,
                         model_key: str, out: Path) -> None:
    """
    PCA-2D of the FINAL transformer layer, coloured four ways in a 2×2 grid.
    This is the single-panel equivalent of a t-SNE — fast and interpretable.
    """
    final = hs[:, -1, :]
    xy    = _pca2(final)

    person_cats = sorted(meta["person"].unique())
    person_pal  = dict(zip(person_cats, sns.color_palette("tab20", len(person_cats))))

    schemes = [
        ("protagonist_gender", GEN_COLORS,   "Protagonist Gender"),
        ("region",             REG_COLORS,   "Cultural Region"),
        ("model_family",       FAM_COLORS,   "Model Family"),
        ("person",             person_pal,   "Narrator Role"),
    ]

    fig, axes = plt.subplots(2, 2, figsize=(16, 13))
    fig.suptitle(
        f"Final-Layer Hidden States : PCA-2D\n{model_key}  "
        f"({hs.shape[0]} stories, layer {hs.shape[1]-1}, dim {hs.shape[2]})",
        fontsize=13, fontweight="bold",
    )
    for ax, (col, colors, title) in zip(axes.flat, schemes):
        for val, color in colors.items():
            mask = (meta[col] == val).values
            if not mask.any():
                continue
            ax.scatter(xy[mask, 0], xy[mask, 1],
                       c=color, alpha=0.40, s=8, linewidths=0, label=val)
        ax.set_title(title, fontweight="bold")
        ax.set_xlabel("PC 1"); ax.set_ylabel("PC 2")
        ax.legend(markerscale=3, fontsize=7, loc="best",
                  framealpha=0.7, edgecolor="none")
        ax.set_facecolor("#f8f8f8")

    plt.tight_layout()
    _save(fig, out / "01_pca_final_layer.png")


def plot_tsne_layer_panels(hs: np.ndarray, meta: pd.DataFrame,
                           model_key: str, panel_layers: list[int],
                           out: Path) -> None:
    """
    t-SNE at selected layers, coloured by protagonist gender.
    Shows how cluster structure evolves from embedding - final layer.
    """
    fig, axes = plt.subplots(1, len(panel_layers),
                             figsize=(len(panel_layers) * 4.2, 4.5))
    if len(panel_layers) == 1:
        axes = [axes]

    fig.suptitle(
        f"t-SNE at Selected Layers : {model_key}\n"
        "Does gender separation grow with depth?",
        fontsize=12, fontweight="bold",
    )
    for ax, layer_idx in zip(axes, panel_layers):
        print(f"    t-SNE layer {layer_idx} …")
        xy = _tsne2(hs[:, layer_idx, :])

        for gender, color in GEN_COLORS.items():
            mask = (meta["protagonist_gender"] == gender).values
            ax.scatter(xy[mask, 0], xy[mask, 1],
                       c=color, alpha=0.35, s=6, linewidths=0, label=gender)

        label = "Embedding" if layer_idx == 0 else f"Layer {layer_idx}"
        ax.set_title(label, fontweight="bold")
        ax.set_xticks([]); ax.set_yticks([])
        ax.set_facecolor("#f8f8f8")

    handles = [mpatches.Patch(color=c, label=g) for g, c in GEN_COLORS.items()]
    fig.legend(handles=handles, loc="lower right", fontsize=9,
               framealpha=0.85, ncol=2)
    plt.tight_layout()
    _save(fig, out / "02_tsne_layer_panels.png")


def plot_gender_separation_curve(hs: np.ndarray, meta: pd.DataFrame,
                                 model_key: str, out: Path) -> np.ndarray:
    """
    cosine distance between female/male story centroids
    at every single layer.  Rising curve = bias deepens with network depth.
    """
    n_layers = hs.shape[1]
    fm = (meta["protagonist_gender"] == "female").values
    mm = (meta["protagonist_gender"] == "male").values

    dists = np.array([
        _centroid_cos_dist(hs[:, l, :], fm, mm)
        for l in range(n_layers)
    ])

    peak = int(np.argmax(dists))
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(range(n_layers), dists, "o-", color="#C44E52", linewidth=2, markersize=5)
    ax.fill_between(range(n_layers), dists, alpha=0.12, color="#C44E52")
    ax.axvline(peak, color="#C44E52", linestyle="--", alpha=0.7,
               label=f"Peak  layer {peak}  (dist = {dists[peak]:.4f})")
    ax.set_xlabel("Transformer Layer  (0 = embedding)")
    ax.set_ylabel("Cosine Distance\n(female centroid  vs  male centroid)")
    ax.set_title(
        f"Gender Bias Signal Across Transformer Layers : {model_key}\n"
        "Higher = more gender-separated hidden space at that depth",
        fontweight="bold",
    )
    ax.legend(fontsize=9)
    ax.set_xticks(range(n_layers))
    ax.set_facecolor("#f8f8f8")
    plt.tight_layout()
    _save(fig, out / "03_gender_separation_curve.png")
    print(f"    Peak gender separation: layer {peak}  (dist={dists[peak]:.4f})")
    return dists


def plot_probe_accuracy_curve(hs: np.ndarray, meta: pd.DataFrame,
                              model_key: str, out: Path) -> np.ndarray:
    """
    Linear probe (logistic regression, 5-fold CV) at every layer.
    Answers: can we predict protagonist gender from the hidden state?
    Accuracy well above 50 % = gender is encoded at that depth.
    """
    n_layers = hs.shape[1]
    y = (meta["protagonist_gender"] == "female").values.astype(int)
    print(f"    Running linear probe on {n_layers} layers …")

    accs = np.array([_probe_acc(hs[:, l, :], y) for l in range(n_layers)])

    peak = int(np.argmax(accs))
    fig, ax = plt.subplots(figsize=(10, 5))
    colors = ["#C44E52" if i == peak else "#4C72B0" for i in range(n_layers)]
    ax.bar(range(n_layers), accs * 100, color=colors, alpha=0.85, edgecolor="white")
    ax.axhline(50, color="gray", linestyle="--", linewidth=1, label="Chance (50 %)")
    ax.axhline(accs.max() * 100, color="#C44E52", linestyle=":",
               label=f"Peak  {accs.max()*100:.1f} %  @  layer {peak}")
    ax.set_xlabel("Transformer Layer")
    ax.set_ylabel("Probe Accuracy (%)")
    ax.set_title(
        f"Gender Prediction from Hidden States : {model_key}\n"
        "Linear probe (logistic regression, 5-fold CV)",
        fontweight="bold",
    )
    ax.set_xticks(range(n_layers))
    ax.legend(fontsize=9)
    ax.set_ylim(40, min(100, accs.max() * 100 + 5))
    ax.set_facecolor("#f8f8f8")
    plt.tight_layout()
    _save(fig, out / "04_probe_accuracy_curve.png")
    print(f"    Peak probe accuracy:    layer {peak}  ({accs.max()*100:.1f} %)")
    return accs


def plot_region_separation_curve(hs: np.ndarray, meta: pd.DataFrame,
                                 model_key: str, out: Path) -> None:
    """
    Mean pairwise cosine distance between cultural region centroids per layer.
    Low = cultures are conflated; high = culturally distinct representations.
    """
    n_layers = hs.shape[1]
    regions  = [r for r in REG_COLORS if (meta["region"] == r).any()]
    if len(regions) < 2:
        print("    Too few regions --> skipping region separation curve.")
        return

    mean_dists = np.zeros(n_layers)
    for l in range(n_layers):
        centroids = np.array([
            hs[(meta["region"] == r).values, l, :].mean(0) for r in regions
        ])
        mean_dists[l] = pdist(centroids, metric="cosine").mean()

    peak = int(np.argmax(mean_dists))
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(range(n_layers), mean_dists, "s-", color="#55A868", linewidth=2, markersize=5)
    ax.fill_between(range(n_layers), mean_dists, alpha=0.12, color="#55A868")
    ax.axvline(peak, color="#55A868", linestyle="--", alpha=0.7,
               label=f"Peak  layer {peak}  (dist = {mean_dists[peak]:.4f})")
    ax.set_xlabel("Transformer Layer  (0 = embedding)")
    ax.set_ylabel("Mean Pairwise Cosine Distance\n(region centroids)")
    ax.set_title(
        f"Cultural Region Separation Across Transformer Layers : {model_key}\n"
        "Higher = more culturally distinct semantic space at that depth",
        fontweight="bold",
    )
    ax.legend(fontsize=9)
    ax.set_xticks(range(n_layers))
    ax.set_facecolor("#f8f8f8")
    plt.tight_layout()
    _save(fig, out / "05_region_separation_curve.png")
    print(f"    Peak region separation: layer {peak}  (dist={mean_dists[peak]:.4f})")


def plot_interactive_final_layer(hs: np.ndarray, meta: pd.DataFrame,
                                 model_key: str, out: Path) -> None:
    """
    Interactive Plotly scatter of the FINAL layer PCA-2D.
    Hover over any dot to see the story metadata.
    """
    xy = _pca2(hs[:, -1, :])

    fig = go.Figure()
    for gender, color in GEN_COLORS.items():
        mask = (meta["protagonist_gender"] == gender).values
        sub  = meta[mask]
        fig.add_trace(go.Scatter(
            x=xy[mask, 0], y=xy[mask, 1],
            mode="markers",
            name=gender,
            marker=dict(color=color, size=5, opacity=0.55),
            customdata=np.column_stack([
                sub["country"].values,
                sub["person"].values,
                sub["model_key"].values,
                sub["word_count"].values.astype(str),
            ]),
            hovertemplate=(
                "<b>%{name}</b>  ·  %{customdata[2]}<br>"
                "Country: %{customdata[0]}  |  Narrator: %{customdata[1]}<br>"
                "Words: %{customdata[3]}"
                "<extra></extra>"
            ),
        ))
    fig.update_layout(
        title=dict(
            text=(
                f"Final-Layer Hidden States (PCA-2D) : {model_key}<br>"
                f"<span style='font-size:12px'>Layer {hs.shape[1]-1}  |  "
                f"dim {hs.shape[2]}  |  {hs.shape[0]} stories</span>"
            ),
            font=dict(size=14),
        ),
        xaxis_title="PC 1", yaxis_title="PC 2",
        width=1200, height=700,
        plot_bgcolor="#f8f8f8",
        hoverlabel=dict(bgcolor="white", font_size=12),
    )
    path = out / "06_interactive_final_layer.html"
    fig.write_html(str(path))
    print(f"    saved → {path.name}")


def plot_interactive_layer_slider(hs: np.ndarray, meta: pd.DataFrame,
                                  model_key: str, out: Path) -> None:
    """
    Plotly scatter with a layer slider.  Each frame = one layer's PCA-2D
    coloured by signed projection onto the final-layer gender axis.
    Use the Play button to animate through all layers.
    """
    n_layers = hs.shape[1]
    final    = hs[:, -1, :]
    fm = (meta["protagonist_gender"] == "female").values
    mm = (meta["protagonist_gender"] == "male").values
    axis = final[fm].mean(0) - final[mm].mean(0)
    axis /= np.linalg.norm(axis) + 1e-9

    # Fixed PCA basis from the final layer so spatial layout is stable
    pca_basis = PCA(n_components=2, random_state=RANDOM_STATE).fit(final)

    frames, steps = [], []
    for l in range(n_layers):
        layer_vecs = hs[:, l, :]
        xy   = pca_basis.transform(layer_vecs)
        proj = layer_vecs @ axis
        vmin, vmax = float(np.percentile(proj, 5)), float(np.percentile(proj, 95))

        label = "Embedding" if l == 0 else f"Layer {l}"
        frames.append(go.Frame(
            data=[go.Scatter(
                x=xy[:, 0], y=xy[:, 1],
                mode="markers",
                marker=dict(
                    color=proj, colorscale="RdBu", reversescale=True,
                    size=5, opacity=0.6,
                    cmin=vmin, cmax=vmax,
                    colorbar=dict(title="Gender<br>projection"),
                    showscale=True,
                ),
                customdata=np.column_stack([
                    meta["protagonist_gender"].values,
                    meta["country"].values,
                    meta["person"].values,
                    proj.round(4).astype(str),
                ]),
                hovertemplate=(
                    "<b>%{customdata[0]}</b>  ·  %{customdata[2]}<br>"
                    "Country: %{customdata[1]}<br>"
                    "Gender projection: %{customdata[3]}"
                    "<extra></extra>"
                ),
            )],
            name=str(l),
            layout=go.Layout(title_text=(
                f"{model_key} : {label}  |  "
                "Blue = female-space  Red = male-space"
            )),
        ))
        steps.append(dict(
            args=[[str(l)], {"frame": {"duration": 0}, "mode": "immediate",
                             "transition": {"duration": 0}}],
            label=label, method="animate",
        ))

    # Initial frame (embedding layer)
    init_vecs = hs[:, 0, :]
    init_xy   = pca_basis.transform(init_vecs)
    init_proj = init_vecs @ axis

    fig = go.Figure(
        data=[go.Scatter(
            x=init_xy[:, 0], y=init_xy[:, 1],
            mode="markers",
            marker=dict(
                color=init_proj, colorscale="RdBu", reversescale=True,
                size=5, opacity=0.6,
                cmin=float(np.percentile(init_proj, 5)),
                cmax=float(np.percentile(init_proj, 95)),
                colorbar=dict(title="Gender<br>projection"),
            ),
            customdata=np.column_stack([
                meta["protagonist_gender"].values,
                meta["country"].values,
                meta["person"].values,
                init_proj.round(4).astype(str),
            ]),
            hovertemplate=(
                "<b>%{customdata[0]}</b>  ·  %{customdata[2]}<br>"
                "Country: %{customdata[1]}<br>"
                "Gender projection: %{customdata[3]}"
                "<extra></extra>"
            ),
        )],
        frames=frames,
    )
    fig.update_layout(
        title=dict(
            text=(
                f"{model_key} : Embedding Layer  |  "
                "Blue = female-space   Red = male-space<br>"
                "<span style='font-size:11px'>Use the slider or Play to walk "
                "through all transformer layers</span>"
            ),
            font=dict(size=13),
        ),
        xaxis_title="PC 1", yaxis_title="PC 2",
        width=1200, height=750,
        plot_bgcolor="#f8f8f8",
        hoverlabel=dict(bgcolor="white", font_size=12),
        sliders=[dict(
            active=0, steps=steps,
            x=0.05, y=0, len=0.9,
            currentvalue=dict(prefix="Layer: ", font=dict(size=13)),
            transition=dict(duration=0),
        )],
        updatemenus=[dict(
            type="buttons", showactive=False, y=0.05, x=0.0, xanchor="right",
            buttons=[
                dict(label="▶ Play", method="animate",
                     args=[None, {"frame": {"duration": 700}, "fromcurrent": True}]),
                dict(label="⏸ Pause", method="animate",
                     args=[[None], {"frame": {"duration": 0}, "mode": "immediate"}]),
            ],
        )],
    )
    path = out / "07_interactive_layer_slider.html"
    fig.write_html(str(path))
    print(f"    saved → {path.name}")


# Per-model driver 

def run_model(model_key: str, panel_layers: list[int] | None) -> None:
    hs_path   = HS_DIR / f"hidden_states_{model_key}.npy"
    meta_path = HS_DIR / f"extractor_meta_{model_key}.csv"

    if not hs_path.exists():
        print(f"  [skip] {model_key} : {hs_path.name} not found. "
              f"Run hidden_state_extractor_by_model.py first.")
        return

    print(f"  Model: {model_key}")

    hs   = np.load(hs_path)           # (n_stories, n_layers, hidden_dim)
    meta = pd.read_csv(meta_path)
    meta["region"] = meta["country"].map(REGION_MAP)

    # Drop stories where any layer/dim is NaN or Inf (float16 overflow artefacts)
    bad = ~np.isfinite(hs).all(axis=(1, 2))
    if bad.any():
        print(f"  Warning: dropping {bad.sum()} stories with NaN/Inf hidden states.")
        hs   = hs[~bad]
        meta = meta[~bad].reset_index(drop=True)

    n, L, H = hs.shape
    print(f"  Loaded: {n} stories  ×  {L} layers  ×  {H}-dim hidden states")

    if n == 0:
        print(f"  No valid stories — skipping {model_key}. "
              f"Re-extract with bfloat16 (see extractor dtype setting).")
        return

    out = OUT_DIR / model_key
    out.mkdir(parents=True, exist_ok=True)

    # Try to find the HF model ID for the description
    from hidden_state_extractor_by_model import HF_MODEL_MAP
    hf_id = HF_MODEL_MAP.get(model_key, "unknown")

    layers = _panel_layer_indices(L, panel_layers)
    print(f"  t-SNE panel layers: {layers}")

    describe_npy(hs, model_key, hf_id, out)
    plot_pca_final_layer(hs, meta, model_key, out)
    plot_tsne_layer_panels(hs, meta, model_key, layers, out)
    plot_gender_separation_curve(hs, meta, model_key, out)
    plot_probe_accuracy_curve(hs, meta, model_key, out)
    plot_region_separation_curve(hs, meta, model_key, out)
    plot_interactive_final_layer(hs, meta, model_key, out)
    plot_interactive_layer_slider(hs, meta, model_key, out)

    print(f"  All outputs : {out}/")


# Main 

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--model", default=None,
                   help="Single model key to visualise (default: all extracted).")
    p.add_argument("--panel-layers", nargs="+", type=int, default=None,
                   help="Layer indices for the t-SNE panel (default: auto).")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    if args.model:
        run_model(args.model, args.panel_layers)
    else:
        available = sorted(HS_DIR.glob("hidden_states_*.npy"))
        if not available:
            print(f"No .npy files found in {HS_DIR}. "
                  f"Run hidden_state_extractor_by_model.py first.")
            return
        for p in available:
            model_key = p.stem.replace("hidden_states_", "")
            run_model(model_key, args.panel_layers)


if __name__ == "__main__":
    main()
